name: poem_app
description: A new Flutter project for POEM self-check.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  googleapis: ^13.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  http: ^1.1.0
  path_provider: ^2.1.2

  # ä¿®æ­£é€™è£¡ï¼šä½¿ç”¨æœ€æ–°çš„ plus ç‰ˆæœ¬
  # icloud_storage_plus: ^1.0.0  # <--- å…ˆåŠ  # å­—è™Ÿè¨»è§£æŽ‰

  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1
  shared_preferences: ^2.5.3

  flutter_riverpod: ^2.5.1
  intl: ^0.19.0

  pdf: ^3.10.8
  printing: ^5.11.1
  share_plus: ^10.0.0
  font_awesome_flutter: ^10.7.0

  firebase_core: ^3.15.2
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.0

  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  flutter_line_sdk: ^2.6.2
  image_cropper: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/  # å¦‚æžœä½ æœ‰æ”¾ç…§ç‰‡
    - assets/fonts/

  fonts:
    - family: NotoSansTC
      fonts:
        - asset: assets/fonts/NotoSansTC-Regular.ttf
        - asset: assets/fonts/NotoSansTC-Bold.ttf

    - family: NotoSansMath
      fonts:
        - asset: assets/fonts/NotoSansMath-Regular.ttf

    - family: NotoEmoji  # ðŸš€ æ–°å¢ž Emoji å­—é«”å®¶æ—
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf